volumes:
  langgraph-data:
    driver: local
services:
  langgraph-redis:
    image: docker.io/redis:6
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 1s
      retries: 5
  langgraph-postgres:
    image: docker.io/postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - langgraph-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      start_period: 10s
      timeout: 1s
      retries: 5
      interval: 5s
  langgraph-api:
    image: ghcr.io/robert/freesearch:latest
    ports:
      - "8123:8000"
    depends_on:
      langgraph-redis:
        condition: service_healthy
      langgraph-postgres:
        condition: service_healthy
    environment:
      # LLM Provider Configuration
      LLM_PROVIDER: ${LLM_PROVIDER:-gemini}
      
      # Google Gemini Configuration
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      
      # OpenAI Configuration
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_API_BASE: ${OPENAI_API_BASE}
      
      # Model Configuration
      QUERY_GENERATOR_MODEL: ${QUERY_GENERATOR_MODEL}
      REFLECTION_MODEL: ${REFLECTION_MODEL}
      ANSWER_MODEL: ${ANSWER_MODEL}
      
      # Research Configuration
      NUMBER_OF_INITIAL_QUERIES: ${NUMBER_OF_INITIAL_QUERIES}
      MAX_RESEARCH_LOOPS: ${MAX_RESEARCH_LOOPS}
      
      # LangSmith Configuration
      LANGSMITH_API_KEY: ${LANGSMITH_API_KEY}
      
      # Database Configuration
      REDIS_URI: redis://langgraph-redis:6379
      POSTGRES_URI: postgres://postgres:postgres@langgraph-postgres:5432/postgres?sslmode=disable
